language: node_js
node_js:
  - "16"
env:
  global:
    - secure: "GlG7iczE4CFh1cC4aSKMVVfRw9xTiojl8kBvrFndCddJwh5s8hAASaoBa5x+z5okiLK6KJmfOMi5fU7/vTwLQZjIhEZwIc2InXmd5wzha2z2+GlToLQIA1C0h1Ja7IixyeOU8XpzXAP+w6GBf3LalrJNwkMoriiuWRjNVC6BgweI6cg+io+7jCIacpmMObgO0ff+afQq58mCSwje+Ep7yzg3yNmJ9p2vZWKCXLRkbcUXDrGqnxGlqKeIs1ow7PMEVEJLZebOEFpjXZSgQCxkgLZCx2F9VAiLwAHgwLxOK5RN/mcsGxFN15V9Y2pOpOzdWKglHDIpYpZvtaHINPmGFU4TxlN5IfXnQF3Ms6HdgvVCZRQK4ARRSds0VR990B5cqvXIam8/JbSb7ZSP/HRLTn19m7CWP9RiYg9QAkLq4hJiW9zZoznPt9+lYlCzqtadsogqX3lLGQspQ2GggtM+k6KAP0E6viqqtv8cYIHvOnG5r0IRWJ0eFSunHfvNVOy2Lmf9Xr5V2e6fiqRltJ+r81AlP4nVP9dkX76ZObnbu6jUkbtC4nqGJQ7Z1DK5Dee4zLqKTtp57TiAc7DzKChmQkuSCVqeIJOxzlyqXM9YLpjbW6qzyPtFfBTjovXDhRqAZ3G4xRqbLQK0ArH0TEOo9pe7GvCxfmr4PFMS20xx3cE="
install:
  - npm ci
  - lerna bootstrap
script:
  - npm run build
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info
  
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true