# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: trino
  labels:
    side: external
    type: statefull
spec:
  containers:
    - name: trino
      image: imazzine/hdml.io-trino:v0.0.0-alpha.12
      ports:
        - containerPort: 8080