# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.volume.name }}
  {{- with .Values.volume.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  storageClassName: {{ .Values.volume.class }}
  accessModes:
    - {{ .Values.volume.access }}
  capacity:
    storage: {{ .Values.volume.capacity }}
  hostPath:
    path: {{ .Values.volume.path }}