# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.hpa.querier.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployments.querier.name }}
  minReplicas: {{ .Values.hpa.querier.minReplicas }}
  maxReplicas: {{ .Values.hpa.querier.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90