# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdml.io
  labels:
    type: data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1M
  hostPath:
    path: /data/hdml.io/