# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    side: internal
    type: stateless
spec:
  type: NodePort
  selector:
    role: gateway
    side: internal
    type: stateless
  ports:
    - name: rest-api
      protocol: TCP
      port: 8888
      targetPort: 8888