# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: pulsar
  labels:
    side: internal
    type: stateless
spec:
  type: ClusterIP
  selector:
    role: pulsar
    side: external
    type: statefull
  ports:
    - name: rest-api
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: driver-api
      protocol: TCP
      port: 6650
      targetPort: 6650