# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: querier
  labels:
    side: internal
    type: stateless
spec:
  type: LoadBalancer
  selector:
    role: querier
    side: internal
    type: stateless
  ports:
    - name: rest-api
      protocol: TCP
      port: 8886
      targetPort: 8886