# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: trino
  labels:
    side: internal
    type: stateless
spec:
  type: LoadBalancer
  selector:
    role: trino
    side: external
    type: statefull
  ports:
    - name: rest-api
      protocol: TCP
      port: 8080
      targetPort: 8080