# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: gateway
  labels:
    type: stateless
spec:
  containers:
    - name: gateway
      image: imazzine/hdml.io-gateway:v0.0.0-alpha.11
      ports:
        - containerPort: 8888