# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: hideway
  labels:
    side: internal
    type: stateless
spec:
  containers:
    - name: hideway
      image: imazzine/hdml.io-hideway:v0.0.0-alpha.12
      ports:
        - containerPort: 8887