# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: hideway
  labels:
    side: internal
    type: stateless
spec:
  type: ClusterIP
  selector:
    role: hideway
    side: internal
    type: stateless
  ports:
    - name: rest-api
      protocol: TCP
      port: 8887
      targetPort: 8887