# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdml.io
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1M
  selector:
    matchLabels:
      type: data