// automatically generated by the FlatBuffers compiler, do not modify


/**
 * Query aggregations enum.
 */
export enum AggType {
  None = 0,
  Count = 1,
  CountDistinct = 2,
  CountDistinctApprox = 3,
  Sum = 4,
  Avg = 5,
  Min = 6,
  Max = 7
}

