// automatically generated by the FlatBuffers compiler, do not modify


/**
 * Deprecated. Delete it.
 */
export enum FileState {
  PROCESSING = 0,
  SCHEMA = 1,
  CHUNK = 2,
  DONE = 3,
  FAIL = 4
}

