// automatically generated by the FlatBuffers compiler, do not modify


/**
 * AggType enum.
 */
export enum AggType {
  Count = 0,
  CountDistinct = 1,
  CountDistinctApprox = 2,
  Sum = 3,
  Avg = 4,
  Min = 5,
  Max = 6
}

