// automatically generated by the FlatBuffers compiler, do not modify


/**
 * JoinType enum.
 */
export enum JoinType {
  Cross = 0,
  Inner = 1,
  Full = 2,
  Left = 3,
  Right = 4,
  FullOuter = 5,
  LeftOuter = 6,
  RightOuter = 7
}

