// automatically generated by the FlatBuffers compiler, do not modify


/**
 * `HDML` network protocol query data types enum.
 */
export enum DataType {
  Int8 = 0,
  Int16 = 1,
  Int32 = 2,
  Int64 = 3,
  Uint8 = 4,
  Uint16 = 5,
  Uint32 = 6,
  Uint64 = 7,
  Float16 = 8,
  Float32 = 9,
  Float64 = 10,
  Decimal = 11,
  Date = 12,
  Time = 13,
  Timestamp = 14,
  Binary = 15,
  Utf8 = 16
}

