// automatically generated by the FlatBuffers compiler, do not modify


/**
 * `HDML` network protocol query decimal data field bit width enum.
 */
export enum DecBitWidth {
  _128 = 0,
  _256 = 1
}

