// automatically generated by the FlatBuffers compiler, do not modify


/**
 * `HDML` network protocol query table types enum.
 */
export enum TableType {
  Json = 0,
  Csv = 1,
  Table = 2,
  Query = 3
}

