// automatically generated by the FlatBuffers compiler, do not modify


/**
 * `HDML` network protocol response file state enum.
 */
export enum FileState {
  PROCESSING = 0,
  SCHEMA = 1,
  CHUNK = 2,
  DONE = 3,
  FAIL = 4
}

