// automatically generated by the FlatBuffers compiler, do not modify


/**
 * Posted query state enum.
 */
export enum QueryState {
  PROCESSING = 0,
  SCHEMA = 1,
  CHUNK = 2,
  DONE = 3,
  FAIL = 4
}

