// automatically generated by the FlatBuffers compiler, do not modify


/**
 * `HDML` network protocol query time unit enum.
 */
export enum TimeUnit {
  second = 0,
  millisecond = 1,
  microsecond = 2,
  nanosecond = 3
}

