// automatically generated by the FlatBuffers compiler, do not modify


/**
 * `HDML` network protocol query filter names enum.
 */
export enum FilterName {
  Equals = 0,
  NotEquals = 1,
  Contains = 2,
  NotContains = 3,
  StartsWith = 4,
  EndsWith = 5,
  Greater = 6,
  GreaterEqual = 7,
  Less = 8,
  LessEqual = 9,
  IsNull = 10,
  IsNotNull = 11,
  Between = 12
}

