// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';


/**
 * Posted query path structure.
 */
export class Path {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Path {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPath(bb:flatbuffers.ByteBuffer, obj?:Path):Path {
  return (obj || new Path()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPath(bb:flatbuffers.ByteBuffer, obj?:Path):Path {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Path()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

uri():string|null
uri(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uri(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPath(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUri(builder:flatbuffers.Builder, uriOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, uriOffset, 0);
}

static endPath(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPath(builder:flatbuffers.Builder, uriOffset:flatbuffers.Offset):flatbuffers.Offset {
  Path.startPath(builder);
  Path.addUri(builder, uriOffset);
  return Path.endPath(builder);
}
}

