// automatically generated by the FlatBuffers compiler, do not modify


export enum Type {
  Int8 = 0,
  Int16 = 1,
  Int32 = 2,
  Int64 = 3,
  Uint8 = 4,
  Uint16 = 5,
  Uint32 = 6,
  Uint64 = 7,
  Float16 = 8,
  Float32 = 9,
  Float64 = 10,
  Binary = 11,
  Utf8 = 12
}

