# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

FROM node:18.16.0-alpine3.18 AS querier

RUN apk add mc rxvt-unicode
RUN npm i -g @hdml/io.querier@latest
RUN ln -s /usr/local/lib/node_modules/@hdml/io.querier/cjs/querier.js /usr/local/bin/querier
RUN chmod +x /usr/local/lib/node_modules/@hdml/io.querier/cjs/querier.js

ENV TERM rxvt-unicode
ENV NODE_ENV production

EXPOSE 8886

CMD ["querier"]