# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Push devtools image

on:
  push:
    paths:
      - '.github/workflows/devtools.yml'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: imazzine/hdml.io-devtools:latest
          file: ./docker/devtools/Dockerfile
          context: .