# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Release Version

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  release_npm:
    runs-on: ubuntu-latest
    container: imazzine/hdml.io-devtools:latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install `hdml` dependencies
        run: npm ci
      - name: Bootstrap `hdml`
        run: npm run bootstrap
      - name: Build `hdml`
        run: HOME=/root npm run build
      - name: Set `npm` token
        run: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish `hdml`
        run: npm run publish