# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Release Version

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  release_npm:
    name: Release `npm` packages
    runs-on: ubuntu-latest
    container: imazzine/hdml.io-devtools:latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install `lerna`
        run: npm i -g lerna@^6.6.2
      - name: Install `hdml` dependencies
        run: npm ci
      - name: Bootstrap `hdml`
        run: npm run bootstrap
      - name: Build `hdml`
        run: HOME=/root npm run build
      - name: Set `npm` token
        run: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish `hdml`
        run: npm run publish

  release_docker_services:
    name: Release `${{ matrix.service }}` service docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [release_npm]
    strategy:
      matrix:
        service:
          - gateway
          - hideway
          - querier
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: imazzine/hdml.io-${{ matrix.service }}:latest
          file: ./docker/services/Dockerfile.${{ matrix.service }}
          context: .