# @author Artem Lytvynov
# @copyright Artem Lytvynov
# @license Apache-2.0

name: Release the new version

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install development dependencies
        run: npm ci
      - name: Install playwright dependencies
        run: npx playwright install-deps
      - name: Bootstrap project
        run: lerna bootstrap
      - name: Build project
        run: npm run build

  
      - name: Publish project
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}