version: "2.2"
services:

  # Apache Pulsar
  pulsar:
    container_name: hdml-pulsar
    image: apachepulsar/pulsar:3.0.0
    ports:
      - "6650:6650"
      - "9090:8080"
    depends_on:
      - trino
    links:
      - trino
    command: bin/pulsar standalone
    restart: always

  # Trino Query Engine
  trino:
    container_name: hdml-trino
    image: trinodb/trino
    ports:
      - "8080:8080"
    volumes:
      - ./.catalog:/etc/trino/catalog
    depends_on:
      - postgres
      # - mysql
      # - mongo
    links:
      - postgres
      # - mysql
      # - mongo
    restart: always

  # Postgres Databse
  postgres:
    container_name: hdml-postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=hdml
      - POSTGRES_USER=hdml
      - POSTGRES_PASSWORD=hdml
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    restart: always

  # MySQL Database
  # mysql:
  #   container_name: hdml-mysql
  #   image: mysql:8
  #   environment:
  #     - MYSQL_DATABASE=hdml
  #     - MYSQL_ROOT_PASSWORD=hdml
  #   command: mysqld --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./.data/mysql:/var/lib/mysql
  #   restart: always

  # Mongo Database
  # mongo:
  #   container_name: hdml-mongo
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: hdml
  #     MONGO_INITDB_ROOT_PASSWORD: hdml
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./.data/mongo:/data/db
  #   restart: always